version: "3.2"

services:
  old_wave-test:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: python -m pytest --cov="."
    volumes:
      - ../:/usr/src/app/
    environment:
      - DEBUGGER=False
      - WEB_APP_VERSION=0.0.0
      - WEP_APP_TITLE=Old Wave FastAPI
      - WEP_APP_DESCRIPTION=Backend to Old Wave with FastAPI
      - ENVIRONMENT=dev
      - POSTGRES_DATABASE_URL=postgres://postgres:postgres@old-wave-db:5432/old_wave_dev
      - POSTGRES_DATABASE_TEST_URL=sqlite://./storage/old_wave_test
      - DEFAULT_DATA=False
      - DEFAULT_DEV_DATA=False
